# Netlify configuration file

# Build settings
[build]
  # Command to build the site
  command = "npm run build"

  # Directory containing the serverless functions
  functions = "netlify/functions"

  # Directory to publish after the build
  publish = "dist"

# Rewrite rule for API requests
[[redirects]]
  # Route all requests from /api/*...
  from = "/api/*"

  # ...to the corresponding Netlify function
  to = "/.netlify/functions/:splat"

  # Return a 200 status code
  status = 200
